### ISSUE TITLE
UnsupportedClassVersionError: net/binggl/ninja/oauth/OauthAuthorizationService

### ISSUE THREAD

**Issue by JesseTG** [bihe/ninja-oauth-google#1]
Means what it says on the tin.  I noticed in the Travis build that you use Java 8, but Google App Engine only uses Java 7.  Is that a mistake?  Here's the stack trace:

```
java.lang.UnsupportedClassVersionError: net/binggl/ninja/oauth/OauthAuthorizationService
	at www.purple.mixxy.conf.Module.configure(Module.java:22)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at ninja.Bootstrap.initInjector(Bootstrap.java:217)
	at ninja.Bootstrap.boot(Bootstrap.java:98)
	at ninja.servlet.NinjaServletListener.createNinjaBootstrap(NinjaServletListener.java:131)
	at ninja.servlet.NinjaServletListener.getInjector(NinjaServletListener.java:109)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
	at ninja.servlet.NinjaServletListener.contextInitialized(NinjaServletListener.java:61)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at ninja.standalone.NinjaJetty.doStart(NinjaJetty.java:150)
	at ninja.standalone.AbstractStandalone.start(AbstractStandalone.java:197)
	at ninja.standalone.AbstractStandalone.start(AbstractStandalone.java:44)
	at ninja.utils.NinjaTestServer.<init>(NinjaTestServer.java:54)
	at ninja.utils.NinjaTestServer.<init>(NinjaTestServer.java:41)
	at ninja.utils.NinjaTestServer.<init>(NinjaTestServer.java:37)
	at ninja.NinjaTest.startupServerAndBrowser(NinjaTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by bihe** [comment]
Yep intentionally only java 8 is supported. 

>Google App Engine only uses Java 7

That's true for now although there is a beta available supporting java 8 -> https://cloud.google.com/appengine/docs/flexible/

**Authentication in appengine:**
Actually it is possible in appengine to get the current Google User without additional libraries (https://cloud.google.com/appengine/docs/java/oauth/, https://cloud.google.com/appengine/docs/java/users/) so I am not quite sure if the ninja-oauth-google module is the best solution for your use case.
